name: kontob_flutter
description: "Kontob - កូនតូប Accessories. Flutter port with GetX."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  url_launcher: ^6.3.2
  url_strategy: ^0.3.0
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/products/
    - assets/images/

  fonts:
    - family: NotoSansKhmer
      fonts:
        - asset: assets/fonts/NotoSansKhmer.ttf


#flutter build web --release --base-href /kontobkh/